VENV := ".venv"
PYTHON := VENV + "/bin/python"

default:
  @just --list

# Build the package (into `dist/`)
build:
  rm -drf dist
  {{PYTHON}} -m build
  rm -drf build

# Publish `dist/*` to pypi
publish:
  {{PYTHON}} -m twine upload dist/*

# Create venv and install requirements
init:
  rm -drf {{VENV}} || :
  python3.11 -m venv {{VENV}}
  {{PYTHON}} -m pip install --upgrade pip
  {{PYTHON}} -m pip install build twine pytest

# Run pytest
test:
  {{PYTHON}} -m pytest