PYTHON := justfile_directory() + "/.venv/bin/python"

default:
  @just --list

# Build the package (into `dist/`)
build:
  rm -drf dist
  {{PYTHON}} -m build
  rm -drf build

# Publish `dist/*` to pypi, then delete
publish:
  {{PYTHON}} -m twine upload dist/*
  rm -drf dist

republish: build publish

# Run pytest
test:
  {{PYTHON}} -m pytest